tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
brew "bat"
brew "bat-extras"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "dos2unix"
brew "exercism"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "glow"
brew "go"
brew "jhead"
brew "jq"
brew "kubernetes-cli"
brew "krew"
brew "kubecolor"
brew "lazygit"
brew "mas"
brew "mosh"
brew "ncdu"
brew "neovim"
brew "node"
brew "pipx"
brew "pre-commit"
brew "ripgrep"
brew "starship"
brew "wget"
brew "yarn"
brew "yq"
brew "yt-dlp"
brew "zoxide"
brew "zsh"
brew "zsh-autopair"
brew "zsh-completions"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-vi-mode"
brew "zsh-you-should-use"
cask "1password"
cask "1password-cli"
cask "backblaze"
cask "discord"
cask "font-dejavu"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "google-chrome"
cask "karabiner-elements"
cask "orbstack"
cask "orion"
cask "raindropio"
cask "raycast"
cask "secretive"
cask "setapp"
cask "visual-studio-code"
cask "wezterm"
mas "Dark Noise", id: 1465439395
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "Screens 5", id: 1663047912
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "UTM", id: 1538878817
