#!/bin/zsh
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# My dotfiles
for i in $HOME/.zsh/*.zsh; do
  source "$i"
done

source ~/.zsh/plugins/wezterm.zsh
source ~/.zsh/plugins/zsh-autoquoter.zsh
ZAQ_PREFIXES=('git commit -m' 'gcm' 'ssh( -[^ ]##)# [^ -][^ ]#'i 'sshnh( -[^ ]##)# [^ -][^ ]#')

source /opt/homebrew/share/zsh-autopair/autopair.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

source /opt/homebrew/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /opt/homebrew/share/zsh-you-should-use/you-should-use.plugin.zsh

typeset -U PATH
