local pick_files = function()
  if vim.fn.finddir('.git', vim.fn.getcwd() .. ';') ~= '' then
    Snacks.picker.git_files()
  else
    Snacks.picker.files()
  end
end

local pick_grep = function()
  if vim.fn.finddir('.git', vim.fn.getcwd() .. ';') ~= '' then
    Snacks.picker.git_grep()
  else
    Snacks.picker.grep()
  end
end

vim.keymap.set("n", "<A-h>", require("smart-splits").resize_left)
vim.keymap.set("n", "<A-j>", require("smart-splits").resize_down)
vim.keymap.set("n", "<A-k>", require("smart-splits").resize_up)
vim.keymap.set("n", "<A-l>", require("smart-splits").resize_right)
vim.keymap.set("n", "<C-\\>", require("smart-splits").move_cursor_previous)
vim.keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left)
vim.keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down)
vim.keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up)
vim.keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right)
vim.keymap.set("n", "<C-n>", "<cmd>bn<cr>", {})
vim.keymap.set("n", "<C-p>", "<cmd>bp<cr>", {})
vim.keymap.set("n", "<c-.>",      function() Snacks.scratch() end, {})
vim.keymap.set("n", "<c-/>",      function() Snacks.terminal() end, {})
vim.keymap.set("n", "<leader>D", function() Snacks.bufdelete(0, { force = true }) end, {})
vim.keymap.set("n", "<leader>P", '"+P', {})
vim.keymap.set("n", "<leader>b", function() Snacks.picker.buffers() end, {})
vim.keymap.set("n", "<leader>d", function() local win_config = vim.api.nvim_win_get_config(0) if win_config.relative ~= "" then vim.api.nvim_win_close(0, true) else Snacks.bufdelete() end end, {})
vim.keymap.set("n", "<leader>fG", function() Snacks.picker.grep_buffers() end, {})
vim.keymap.set("n", "<leader>fP", function() Snacks.picker.projects() end, {})
vim.keymap.set("n", "<leader>fd", function() Snacks.picker.diagnostics_buffer() end, {})
vim.keymap.set("n", "<leader>ff", function() pick_files() end, {})
vim.keymap.set("n", "<leader>fg", function() pick_grep() end, {})
vim.keymap.set("n", "<leader>fi", function() Snacks.picker.grep() end, {})
vim.keymap.set("n", "<leader>fj", function() Snacks.picker.jumps() end, {})
vim.keymap.set("n", "<leader>fl", function() Snacks.picker.loclist() end, {})
vim.keymap.set("n", "<leader>fm", function() Snacks.picker.marks() end, {})
vim.keymap.set("n", "<leader>fq", function() Snacks.picker.qflist() end, {})
vim.keymap.set("n", "<leader>fr", function() Snacks.picker.recent() end, {})
vim.keymap.set("n", "<leader>ft", function() Snacks.explorer.open() end, {})
vim.keymap.set("n", "<leader>fu", function() Snacks.picker.undo() end, {})
vim.keymap.set("n", "<leader>gL", function() Snacks.picker.git_log_line() end, {})
vim.keymap.set("n", "<leader>gS", function() Snacks.picker.git_stash() end, {})
vim.keymap.set("n", "<leader>gd", function() Snacks.picker.git_diff() end, {})
vim.keymap.set("n", "<leader>gf", function() Snacks.picker.git_log_file() end, {})
vim.keymap.set("n", "<leader>gg", function() Snacks.lazygit() end, {})
vim.keymap.set("n", "<leader>gl", function() Snacks.gitbrowse() end, {})
vim.keymap.set("n", "<leader>gl", function() Snacks.picker.git_log() end, {})
vim.keymap.set("n", "<leader>gr", function() Snacks.picker.git_branches() end, {})
vim.keymap.set("n", "<leader>gs", function() Snacks.picker.git_status() end, {})
vim.keymap.set("n", "<leader>nA", "<cmd>NotesAllGrep <CR>", {})
vim.keymap.set("n", "<leader>nF", "<cmd>Notes<CR>", {})
vim.keymap.set("n", "<leader>nG", "<cmd>NotesGrep<CR>", {})
vim.keymap.set("n", "<leader>nJ", "<cmd>JournalGrep<CR>", {})
vim.keymap.set("n", "<leader>nP", "<cmd>ProjectNotes<CR>", {})
vim.keymap.set("n", "<leader>nS", "<cmd>ProjectNote scratch<CR>", {})
vim.keymap.set("n", "<leader>nT", "<cmd>Journal<CR>", {})
vim.keymap.set("n", "<leader>nT", "<cmd>ProjectNote todo<CR>", {})
vim.keymap.set("n", "<leader>na", "<cmd>NotesAllGrep float<CR>", {})
vim.keymap.set("n", "<leader>nf", "<cmd>Notes float<CR>", {})
vim.keymap.set("n", "<leader>ng", "<cmd>NotesGrep float<CR>", {})
vim.keymap.set("n", "<leader>nj", "<cmd>JournalGrep float<CR>", {})
vim.keymap.set("n", "<leader>nn", "<cmd>LastNote float<CR>", {})
vim.keymap.set("n", "<leader>np", "<cmd>ProjectNotes float<CR>", {})
vim.keymap.set("n", "<leader>ns", "<cmd>ProjectNote scratch float<CR>", {})
vim.keymap.set("n", "<leader>nt", "<cmd>Journal float<CR>", {})
vim.keymap.set("n", "<leader>nt", "<cmd>ProjectNote todo float<CR>", {})
vim.keymap.set("n", "<leader>p", '"+p', {})
vim.keymap.set("n", "<leader>un", '<cmd>set numbers!<CR>', {})
vim.keymap.set("n", "<leader>wo", "<C-w>o", {})
vim.keymap.set("n", "<leader>wp", "<cmd>pclose<cr>", {})
vim.keymap.set("n", "<leader>wz", "<C-w>|<C-w>_", {})
vim.keymap.set("n", "<leader>y", '"+y', {})
vim.keymap.set("n", "ZZ", "<cmd>wqa!<cr>", {})
vim.keymap.set("n", "[[",         function() Snacks.words.jump(-vim.v.count1) end, {})
vim.keymap.set("n", "[l", "<cmd>lprevious<CR>", {})
vim.keymap.set("n", "[q", "<cmd>cprevious<CR>", {})
vim.keymap.set("n", "]]",         function() Snacks.words.jump(vim.v.count1) end, {})
vim.keymap.set("n", "]l", "<cmd>lnext<CR>", {})
vim.keymap.set("n", "]q", "<cmd>cnext<CR>", {})

vim.keymap.set("x", "<leader>s", ":'<,'>sort i<Cr>", {})
vim.keymap.set("x", "<leader>y", '"+y', {})
