#!/bin/sh
source $HOME/.config/i3/colors

BAT="${BLOCK_INSTANCE:-BAT0}"
upower="$(upower -i /org/freedesktop/UPower/devices/battery_${BAT})"
status="$(echo "$upower" | grep state | awk '{print $2}')"
watts="$(echo "$upower" | grep energy-rate | awk '{printf "%.2fw", $2}')"
percentage="$(echo "$upower" | grep percentage | awk '{print $2}')"

if [ "$status" = "charging" ]; then
  tte=$(echo "$upower" | grep 'time to full' | awk '$5>1 {print $4substr($5,1,1)}')
else
  tte=$(echo "$upower" | grep 'time to empty' | awk '$5>1 {print $4substr($5,1,1)}')
fi

if [ "${tte}" ]; then
percent="${percentage} (${tte})"
else
percent="${percentage}"
fi

widget '\uf5df' "$percent"
widget '\uf0e7' "$watts"
