#!/bin/bash
source $HOME/.config/i3/colors

if pactl get-sink-mute @DEFAULT_SINK@ | grep -q yes; then
  volume=MUTE
  icon='\uf6a9'

else
  volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')
  icon='\uf028'
fi

widget "$icon" "$volume"
