#!/bin/sh
source $HOME/.config/i3/colors

BAT="${BLOCK_INSTANCE:-BAT0}"
upower="$(upower -b)"
status="$(echo "$upower" | grep state | awk '{print $2}')"
percentage="$(echo "$upower" | grep percentage | awk '{print $2}' | cut -d. -f1)"

tte=$(echo "$upower" | grep 'time to' | awk '{print $4}')

if [ "${tte}" ]; then
  if [[ "$(echo "$upower" | grep 'time to' | awk '{print $5}')" == "minutes" ]]; then
    hour="0"
    min="$(printf %.0f $tte)"
  else
    left=$(echo $tte \* 60 | bc)
    hour=$(echo $left / 60 | bc)
    min=$(echo $left % 60 | bc | cut -d. -f1)
  fi

  percent="${hour}:$(printf "%02d" "$min") (${percentage})"
else
  percent="${percentage}"
fi

widget '\uf5df' "$percent"
