#!/bin/bash
source $HOME/.config/i3/colors

current_profile="$(powerprofilesctl get 2>/dev/null)"

if [[ "$current_profile" == "balanced" ]]; then
  icon=" "
elif [[ "$current_profile" == "performance" ]]; then
  icon=""
elif [[ "$current_profile" == "power-saver" ]]; then
  icon=""
else
  icon='\uf2db'
fi

cpuusage="$(mpstat 1 1 | tail -n1 | awk '{printf "%.1f%%", 100 - $12}')"

widget "$icon" $cpuusage
