#!/bin/sh
source $HOME/.config/i3/colors

BAT="${BLOCK_INSTANCE:-BAT1}"
upower="$(upower -i /org/freedesktop/UPower/devices/battery_${BAT})"
status="$(echo "$upower" | grep state | awk '{print $2}')"
watts="$(echo "$upower" | grep energy-rate | awk '{printf "%.2fw", $2}')"
percentage="$(echo "$upower" | grep percentage | awk '{print $2}')"

if [ "$status" = "charging" ]; then
  tte=$(echo "$upower" | grep 'time to full' | awk '{print $4}')
else
  tte=$(echo "$upower" | grep 'time to empty' | awk '{print $4}')
fi
left=$(echo $tte \* 60 | bc)
hour=$(echo $left / 60 | bc)
min=$(echo $left % 60 | bc | cut -d. -f1)


if [ "${tte}" ]; then
percent="${hour}:${min} (${percentage})"
else
percent="${percentage}"
fi

echo $(widget '\uf5df' "$percent")$(widget '\uf0e7' "$watts")
