#!/bin/bash
source $HOME/.config/i3/colors

#------------------------------------------------------------------------

# if no interface is found, use the first device with a global scope
INTERFACE="${BLOCK_INSTANCE:-wlan0}"
SSID=$(iw dev "$INTERFACE" info | grep ssid | sed 's/.*ssid //')

widget '\uf1eb' "$SSID"
