#!/bin/bash
source "$HOME/.config/i3/colors"
CPU=hwmon5/temp1_input
NVME=hwmon3/temp2_input
WIFI=hwmon6/temp1_input

function get_temp() {
awk '{printf "%2.0f°\n", $1/1000}' /sys/class/hwmon/$1
}

cpu=$(get_temp $CPU)

if [[ "$cpu" ]]; then
  widget '\uf2c9' "$cpu"

  if [[ "$BLOCK_BUTTON" ]]; then
    output="
 CPU: $cpu
NVME: $(get_temp $NVME)
WIFI: $(get_temp $WIFI)
"
    notify-send "Temperatures" "$output"
  fi
fi
