#!/bin/sh
source $HOME/.config/i3/colors

BAT="${BLOCK_INSTANCE:-BAT0}"
upower="$(upower -i /org/freedesktop/UPower/devices/battery_${BAT})"
watts="$(echo "$upower" | grep energy-rate | awk '{printf "%.2fw", $2}')"

echo $(widget '\uf0e7' "$watts")
