zstyle :plugin:fast-syntax-highlighting theme "catppuccin-latte"
typeset -g FAST_THEME_NAME="catppuccin-latte"
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedefault]:=fg=#4c4f69}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteunknown-token]:=fg=#d20f39,bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattereserved-word]:=fg=#8839ef}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattealias]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesuffix-alias]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattebuiltin]:=fg=#8839ef}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattefunction]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecommand]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteprecommand]:=fg=#8839ef}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecommandseparator]:=fg=#179299}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattehashed-command]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattepath]:=fg=#dc8a78}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattepath_pathseparator]:=fg=#dc8a78}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteglobbing]:=fg=#ea76cb}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteglobbing-ext]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattehistory-expansion]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesingle-hyphen-option]:=fg=#179299}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedouble-hyphen-option]:=fg=#179299}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteback-quoted-argument]:=fg=#179299}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesingle-quoted-argument]:=fg=#40a02b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedouble-quoted-argument]:=fg=#40a02b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedollar-quoted-argument]:=fg=#40a02b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteback-or-dollar-double-quoted-argument]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteback-dollar-quoted-argument]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteredirection]:=fg=#179299}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecomment]:=fg=#9ca0b0}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattevariable]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattemathvar]:=fg=#ea76cb}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattemathnum]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattematherr]:=fg=#d20f39,bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteassign-array-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattefor-loop-variable]:=fg=#4c4f69}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattefor-loop-number]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattefor-loop-operator]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattefor-loop-separator]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteexec-descriptor]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattehere-string-tri]:=fg=#5c5f77}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattehere-string-text]:=fg=#5c5f77}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattehere-string-var]:=fg=#5c5f77}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesecondary]:=}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecase-input]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecase-parentheses]:=fg=#7c7f93}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecase-condition]:=fg=#7287fd}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattecorrect-subtle]:=fg=#7287fd}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteincorrect-subtle]:=fg=#e64553}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesubtle-bg]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattepath-to-dir]:=fg=#dc8a78}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattepaired-bracket]:=bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattebracket-level-1]:=fg=#d20f39}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattebracket-level-2]:=fg=#df8e1d}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattebracket-level-3]:=fg=#209fb5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteglobal-alias]:=fg=#1e66f5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesubcommand]:=fg=#209fb5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattesingle-sq-bracket]:=fg=#df8e1d}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedouble-sq-bracket]:=fg=#df8e1d}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-lattedouble-paren]:=fg=#40a02b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteoptarg-string]:=fg=#40a02b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latteoptarg-number]:=fg=#fe640b}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-latterecursive-base]:=fg=#4c4f69}
