return {
  {
    "burnskp/notes.nvim",
    opts = {
      notesDir = "$XDG_DATA_HOME/obsidian/main",
      projectNotesDir = "$XDG_DATA_HOME/obsidian/main/projects",
      journalDir = "$XDG_DATA_HOME/obsidian/main/journal",
      git = {
        auto_commit = false,
        auto_push = false,
      },
    },
    cmd = {
      "CreateNote",
      "Journal",
      "JournalFind",
      "JournalGrep",
      "LastNote",
      "Notes",
      "NotesAll",
      "NotesAllGrep",
      "NotesGrep",
      "ProjectNote",
      "ProjectNotes",
      "ProjectNotesGrep",
    },
    keys = {
      { "<leader>na", "<cmd>NotesAllGrep float<CR>", desc = "Grep All Notes (Float)" },
      { "<leader>nA", "<cmd>NotesAllGrep <CR>", desc = "Grep All Notes" },
      { "<leader>nf", "<cmd>Notes float<CR>", desc = "Find Notes (Float)" },
      { "<leader>nF", "<cmd>Notes<CR>", desc = "Find Notes" },
      { "<leader>ng", "<cmd>NotesGrep float<CR>", desc = "Grep Notes (Float)" },
      { "<leader>nG", "<cmd>NotesGrep<CR>", desc = "Grep Notes" },
      { "<leader>nn", "<cmd>LastNote float<CR>", desc = "Open Last Note (Float)" },
      { "<leader>np", "<cmd>ProjectNotes float<CR>", desc = "Find Project Notes (Float)" },
      { "<leader>nP", "<cmd>ProjectNotes<CR>", desc = "Find Project Notes" },
      { "<leader>ns", "<cmd>ProjectNote scratch float<CR>", desc = "Project Note - Scratch (Float)" },
      { "<leader>nS", "<cmd>ProjectNote scratch<CR>", desc = "Grep Project NotNote - Scratch" },
      { "<leader>nt", "<cmd>ProjectNote todo float<CR>", desc = "Project Note - Todo (Float)" },
      { "<leader>nT", "<cmd>ProjectNote todo<CR>", desc = "Grep Project NotNote - Todo" },
      { "<leader>nt", "<cmd>Journal float<CR>", desc = "Today's Journal (Float)" },
      { "<leader>nT", "<cmd>Journal<CR>", desc = "Today's Journal" },
      { "<leader>nj", "<cmd>JournalGrep float<CR>", desc = "Grep Journal Entries (Float)" },
      { "<leader>nJ", "<cmd>JournalGrep<CR>", desc = "Grep Journal Entries" },
    },
  },
}
