#!/bin/sh
source $HOME/.config/i3/colors

BAT="${BLOCK_INSTANCE:-BAT0}"
upower="$(upower -i /org/freedesktop/UPower/devices/battery_${BAT})"
status="$(echo "$upower" | grep state | awk '{print $2}')"
watts="$(echo "$upower" | grep energy-rate | awk '{printf "%.2fw", $2}')"
percentage="$(echo "$upower" | grep percentage | awk '{print $2}')"

GRAY="<span rise='2000' foreground='$foreground' background='$background'>"
BLUE="<span foreground='$foreground' background='$background'>"
SPACER="<span font='6'> </span>"
COLOREND="</span>"
END="<span font='8'>  </span>"

if [ "$status" = "charging" ]; then
  label="\uf5df"
  tte=$(echo "$upower" | grep 'time to full' | awk '$5>1 {print $4substr($5,1,1)}')
else
  label="\uf5df"
  tte=$(echo "$upower" | grep 'time to empty' | awk '$5>1 {print $4substr($5,1,1)}')
fi

if [ "${tte}" ]; then
TEXT="${percentage} (${tte})"
else
TEXT="${percentage}"
fi

echo -e "${GRAY}  ${label} ${TEXT} ${COLOREND}${END}${GRAY}  \uf0e7 ${watts} ${COLOREND}${END}"
