keybindings: vi
model: copilot:gpt-5
repl_prelude: "session:temp"
save_session: false
stream: true
clients:
  - type: openai-compatible
    name: copilot
    api_key: "null"
    api_base: https://api.githubcopilot.com
    patch:
      chat_completions:
        '.*':
          headers:
            Copilot-Integration-Id: vscode-chat
            Editor-Version: aichat/0.1.0
