auto_sync = false
update_check = false
ctrl_n_shortcuts = true
style = "full"
enter_accept = true
keymap_mode = "vim-insert"

[stats]
common_subcommands = [
  "docker",
  "git",
  "go",
  "kubectl",
  "kubecolor",
  "podman",
  "brew",
]
