vim.keymap.set("n", "<C-n>", "<cmd>bnext<cr>", { desc = "Next Buffer" })
vim.keymap.set("n", "<C-p>", "<cmd>bprevious<cr>", { desc = "Previous Buffer" })
vim.keymap.set("n", "<leader>P", '"+P', {})
vim.keymap.set("n", "<leader>P", '"+{', { desc = "Paste from System Clipboard" })
vim.keymap.set("n", "<leader>c", "<cmd>close<CR>", {})
vim.keymap.set("n", "<leader>d", "<cmd>BufferClose<CR>", {})
vim.keymap.set("n", "<leader>e", "<cmd>lua vim.diagnostic.open_float()<CR>", { desc = "Show Diagnostics" })
vim.keymap.set("n", "<leader>p", '"+p', { desc = "Paste from System Clipboard" })
vim.keymap.set("n", "<leader>p", '"+p', {})
vim.keymap.set("n", "<leader>wo", "<C-w>o", {})
vim.keymap.set("n", "<leader>wp", "<cmd>pclose<cr>", {})
vim.keymap.set("n", "<leader>wz", "<C-w>|<C-w>_", {})
vim.keymap.set("n", "<leader>y", '"+y', {})
vim.keymap.set("n", "ZZ", "<cmd>wqa!<cr>", {})
vim.keymap.set("n", "[l", "<cmd>lprevious<CR>", {})
vim.keymap.set("n", "[q", "<cmd>cprevious<CR>", {})
vim.keymap.set("n", "]l", "<cmd>lnext<CR>", {})
vim.keymap.set("n", "]q", "<cmd>cnext<CR>", {})
vim.keymap.set({ "n", "v" }, "<leader>y", '"+y', { desc = "Yank to System Clipboard" })
